#!/usr/bin/env node
/**
 * Interactive .env.local setup for the Optimizely SaaS CMS demo.
 * Run: npm run setup
 * Validate only: npm run setup -- --validate
 */

import { createInterface } from 'node:readline/promises'
import { stdin as input, stdout as output } from 'node:process'
import { copyFile, readFile, writeFile, access } from 'node:fs/promises'
import { constants } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const rootDir = path.join(__dirname, '..')
const examplePath = path.join(rootDir, '.env.example')
const envPath = path.join(rootDir, '.env.local')

const validateOnly = process.argv.includes('--validate')
const isInteractive = Boolean(process.stdin.isTTY) && !validateOnly

function trimTrailingSlash(url) {
  return url.replace(/\/+$/, '')
}

function parseEnv(content) {
  const values = {}
  for (const line of content.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eq = trimmed.indexOf('=')
    if (eq === -1) continue
    values[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim()
  }
  return values
}

function buildEnvFile(values) {
  const lines = [
    '# Generated by npm run setup — edit as needed',
    '# Docs: README.md → Environment variables',
    '',
    '# CMS Admin → Settings → Optimizely Graph → Render Content → Single Key',
    `NEXT_PUBLIC_SDK_KEY=${values.NEXT_PUBLIC_SDK_KEY}`,
    '',
    '# CMS Admin → browser address bar (no trailing slash)',
    `NEXT_PUBLIC_OPTIMIZELY_CMS_URL=${values.NEXT_PUBLIC_OPTIMIZELY_CMS_URL}`,
    '',
    '# CMS Admin → Content tree → Main Website → ID in contentdata:/// link',
    `NEXT_PUBLIC_OPTIMIZELY_CMS_ROOT_NODE_ID=${values.NEXT_PUBLIC_OPTIMIZELY_CMS_ROOT_NODE_ID}`,
    '',
    '# CMS Admin → Content tree → Main Website → URL path',
    `OPTIMIZELY_HOMEPAGE_URL=${values.OPTIMIZELY_HOMEPAGE_URL}`,
    '',
    '# CMS Admin → Settings → API Keys → Manage Content API (server-only — for /import)',
    `OPTIMIZELY_CMS_CLIENT_ID=${values.OPTIMIZELY_CMS_CLIENT_ID || ''}`,
    `OPTIMIZELY_CMS_CLIENT_SECRET=${values.OPTIMIZELY_CMS_CLIENT_SECRET || ''}`,
    '',
    '# Content tree → /poc page → content key (GUID, no hyphens)',
    `OPTIMIZELY_POC_PARENT_CONTENT_KEY=${values.OPTIMIZELY_POC_PARENT_CONTENT_KEY || ''}`,
    '',
    '# Page content type key to create (e.g. poc_page_type)',
    `OPTIMIZELY_POC_PAGE_TYPE_KEY=${values.OPTIMIZELY_POC_PAGE_TYPE_KEY || 'poc_page_type'}`,
    '',
    '# Locale for new CMS content versions',
    `OPTIMIZELY_CMS_LOCALE=${values.OPTIMIZELY_CMS_LOCALE || 'en'}`,
    '',
  ]

  return lines.join('\n')
}

async function fileExists(filePath) {
  try {
    await access(filePath, constants.F_OK)
    return true
  } catch {
    return false
  }
}

async function validateGraph(sdkKey, homepageUrl) {
  const query = `
    query GetHomepage {
      BlankExperience(
        where: {
          _metadata: {
            url: { default: { eq: "${homepageUrl}" } }
          }
        }
        limit: 1
      ) {
        total
        items {
          _metadata { displayName url { default } }
        }
      }
    }
  `

  const response = await fetch(`https://cg.optimizely.com/content/v2?auth=${sdkKey}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ query }),
  })

  const data = await response.json()

  if (!response.ok || data.errors) {
    throw new Error(data.errors?.[0]?.message || `HTTP ${response.status}`)
  }

  const total = data.data?.BlankExperience?.total ?? 0
  const name = data.data?.BlankExperience?.items?.[0]?._metadata?.displayName
  return { total, name }
}

async function runGraphCheck(sdkKey, homepageUrl) {
  if (!sdkKey || !homepageUrl) {
    console.log('⚠ Skipping Graph check — NEXT_PUBLIC_SDK_KEY or OPTIMIZELY_HOMEPAGE_URL is empty.')
    return
  }

  try {
    console.log('Calling Optimizely Graph...')
    const { total, name } = await validateGraph(sdkKey, homepageUrl)
    if (total > 0) {
      console.log(`✓ Found homepage: "${name}" at ${homepageUrl}`)
    } else {
      console.log(`⚠ Graph responded but no BlankExperience at ${homepageUrl}`)
      console.log('  Check OPTIMIZELY_HOMEPAGE_URL matches Main Website → URL in CMS.')
    }
  } catch (error) {
    console.log(`⚠ Graph check failed: ${error.message}`)
    console.log('  Verify NEXT_PUBLIC_SDK_KEY and that Graph sync is complete.')
  }
}

async function loadExistingValues() {
  if (await fileExists(envPath)) {
    return parseEnv(await readFile(envPath, 'utf8'))
  }
  if (await fileExists(examplePath)) {
    return parseEnv(await readFile(examplePath, 'utf8'))
  }
  return {}
}

async function mainInteractive() {
  const rl = createInterface({ input, output })

  async function ask(question, defaultValue = '') {
    const suffix = defaultValue ? ` [${defaultValue}]` : ''
    const answer = (await rl.question(`${question}${suffix}: `)).trim()
    return answer || defaultValue
  }

  console.log('\nOptimizely SaaS CMS demo — .env.local setup\n')

  let existing = {}
  if (await fileExists(envPath)) {
    const overwrite = (await ask('.env.local already exists. Overwrite? (y/N)', 'n')).toLowerCase()
    if (overwrite !== 'y' && overwrite !== 'yes') {
      existing = parseEnv(await readFile(envPath, 'utf8'))
      console.log('Keeping existing values as defaults.\n')
    }
  } else if (await fileExists(examplePath)) {
    await copyFile(examplePath, envPath)
    existing = parseEnv(await readFile(examplePath, 'utf8'))
    console.log('Created .env.local from .env.example\n')
  }

  const sdkKey = await ask(
    'NEXT_PUBLIC_SDK_KEY (Optimizely Graph → Render Content → Single Key)',
    existing.NEXT_PUBLIC_SDK_KEY || ''
  )

  let cmsUrl = await ask(
    'NEXT_PUBLIC_OPTIMIZELY_CMS_URL (CMS admin URL, no trailing slash)',
    existing.NEXT_PUBLIC_OPTIMIZELY_CMS_URL || ''
  )
  cmsUrl = trimTrailingSlash(cmsUrl)

  const rootNodeId = await ask(
    'NEXT_PUBLIC_OPTIMIZELY_CMS_ROOT_NODE_ID (Main Website content tree ID, e.g. 7)',
    existing.NEXT_PUBLIC_OPTIMIZELY_CMS_ROOT_NODE_ID || '7'
  )

  const homepageUrl = await ask(
    'OPTIMIZELY_HOMEPAGE_URL (Main Website URL path in Graph, e.g. /en/)',
    existing.OPTIMIZELY_HOMEPAGE_URL || '/en/'
  )

  const configureImport = (
    await ask('Configure Content Import (/import)? (y/N)', existing.OPTIMIZELY_CMS_CLIENT_ID ? 'y' : 'n')
  ).toLowerCase()

  let clientId = existing.OPTIMIZELY_CMS_CLIENT_ID || ''
  let clientSecret = existing.OPTIMIZELY_CMS_CLIENT_SECRET || ''
  let parentKey = existing.OPTIMIZELY_POC_PARENT_CONTENT_KEY || ''
  let pageTypeKey = existing.OPTIMIZELY_POC_PAGE_TYPE_KEY || 'poc_page_type'
  let cmsLocale = existing.OPTIMIZELY_CMS_LOCALE || 'en'

  if (configureImport === 'y' || configureImport === 'yes') {
    console.log('\nContent Import — Manage Content API (server-only, never NEXT_PUBLIC_)\n')
    clientId = await ask(
      'OPTIMIZELY_CMS_CLIENT_ID (Settings → API Keys → Client ID)',
      clientId
    )
    clientSecret = await ask(
      'OPTIMIZELY_CMS_CLIENT_SECRET (Settings → API Keys → Client secret)',
      clientSecret
    )
    parentKey = await ask(
      'OPTIMIZELY_POC_PARENT_CONTENT_KEY (/poc page content key, no hyphens)',
      parentKey
    )
    pageTypeKey = await ask(
      'OPTIMIZELY_POC_PAGE_TYPE_KEY (page type to create)',
      pageTypeKey
    )
    cmsLocale = await ask('OPTIMIZELY_CMS_LOCALE (locale for new pages)', cmsLocale)
  }

  const values = {
    NEXT_PUBLIC_SDK_KEY: sdkKey,
    NEXT_PUBLIC_OPTIMIZELY_CMS_URL: cmsUrl,
    NEXT_PUBLIC_OPTIMIZELY_CMS_ROOT_NODE_ID: rootNodeId,
    OPTIMIZELY_HOMEPAGE_URL: homepageUrl,
    OPTIMIZELY_CMS_CLIENT_ID: clientId,
    OPTIMIZELY_CMS_CLIENT_SECRET: clientSecret,
    OPTIMIZELY_POC_PARENT_CONTENT_KEY: parentKey,
    OPTIMIZELY_POC_PAGE_TYPE_KEY: pageTypeKey,
    OPTIMIZELY_CMS_LOCALE: cmsLocale,
  }

  await writeFile(envPath, buildEnvFile(values), 'utf8')
  console.log(`\nWrote ${envPath}`)

  const runCheck = (await ask('\nTest connection to Optimizely Graph now? (Y/n)', 'y')).toLowerCase()
  if (runCheck !== 'n' && runCheck !== 'no') {
    await runGraphCheck(sdkKey, homepageUrl)
  }

  console.log('\nNext steps:')
  console.log('  npm run dev')
  console.log('  Open http://localhost:3000/poc')
  if (values.OPTIMIZELY_CMS_CLIENT_ID && values.OPTIMIZELY_POC_PARENT_CONTENT_KEY) {
    console.log('  Open http://localhost:3000/import — create POC pages via CMS API')
  }
  console.log('  See POC_START_HERE.md for a Day 1 checklist\n')

  await rl.close()
}

async function mainNonInteractive() {
  console.log('\nOptimizely SaaS CMS demo — .env.local setup\n')

  if (validateOnly) {
    console.log('Validate mode — checking existing .env.local\n')
  } else {
    console.log('Non-interactive mode — refresh .env.local from existing values')
    console.log('(Run in a terminal without piping for interactive prompts)\n')
  }

  const existing = await loadExistingValues()

  if (!existing.NEXT_PUBLIC_SDK_KEY && !(await fileExists(envPath))) {
    if (await fileExists(examplePath)) {
      await copyFile(examplePath, envPath)
      console.log('Created .env.local from .env.example')
      console.log('Fill in values, then run: npm run setup -- --validate\n')
      return
    }
    console.error('No .env.local found. Copy .env.example to .env.local first.\n')
    process.exit(1)
  }

  const values = {
    NEXT_PUBLIC_SDK_KEY: existing.NEXT_PUBLIC_SDK_KEY || '',
    NEXT_PUBLIC_OPTIMIZELY_CMS_URL: trimTrailingSlash(existing.NEXT_PUBLIC_OPTIMIZELY_CMS_URL || ''),
    NEXT_PUBLIC_OPTIMIZELY_CMS_ROOT_NODE_ID: existing.NEXT_PUBLIC_OPTIMIZELY_CMS_ROOT_NODE_ID || '7',
    OPTIMIZELY_HOMEPAGE_URL: existing.OPTIMIZELY_HOMEPAGE_URL || '/en/',
    OPTIMIZELY_CMS_CLIENT_ID: existing.OPTIMIZELY_CMS_CLIENT_ID || '',
    OPTIMIZELY_CMS_CLIENT_SECRET: existing.OPTIMIZELY_CMS_CLIENT_SECRET || '',
    OPTIMIZELY_POC_PARENT_CONTENT_KEY: existing.OPTIMIZELY_POC_PARENT_CONTENT_KEY || '',
    OPTIMIZELY_POC_PAGE_TYPE_KEY: existing.OPTIMIZELY_POC_PAGE_TYPE_KEY || 'poc_page_type',
    OPTIMIZELY_CMS_LOCALE: existing.OPTIMIZELY_CMS_LOCALE || 'en',
  }

  if (!validateOnly) {
    await writeFile(envPath, buildEnvFile(values), 'utf8')
    console.log(`Wrote ${envPath}\n`)
  }

  console.log('Configuration:')
  console.log(`  NEXT_PUBLIC_OPTIMIZELY_CMS_URL=${values.NEXT_PUBLIC_OPTIMIZELY_CMS_URL || '(empty)'}`)
  console.log(`  NEXT_PUBLIC_OPTIMIZELY_CMS_ROOT_NODE_ID=${values.NEXT_PUBLIC_OPTIMIZELY_CMS_ROOT_NODE_ID}`)
  console.log(`  OPTIMIZELY_HOMEPAGE_URL=${values.OPTIMIZELY_HOMEPAGE_URL}`)
  console.log(`  NEXT_PUBLIC_SDK_KEY=${values.NEXT_PUBLIC_SDK_KEY ? '(set)' : '(empty)'}`)
  console.log(`  Content Import configured=${values.OPTIMIZELY_CMS_CLIENT_ID && values.OPTIMIZELY_POC_PARENT_CONTENT_KEY ? 'yes' : 'no'}\n`)

  await runGraphCheck(values.NEXT_PUBLIC_SDK_KEY, values.OPTIMIZELY_HOMEPAGE_URL)

  console.log('\nNext steps:')
  console.log('  npm run dev')
  console.log('  Open http://localhost:3000\n')
}

;(async () => {
  try {
    if (isInteractive) {
      await mainInteractive()
    } else {
      await mainNonInteractive()
    }
  } catch (error) {
    console.error(error)
    process.exit(1)
  }
})()
